setwd("D:/APU/APU-main/Lab2")

install.packages("data.tree")
install.packages("formattable")
install.packages("DiagrammeR")
install.packages("D:/APU/APU-main/Lab2/ahp_0.2.12.tar.gz", repos=NULL, type = "source")
install.packages("readr")
library(ahp)
library(data.tree)
library(formattable)
library(DiagrammeR)
library(readr)

ahpFile <- system.file("extdata", "ipads.ahp", package="ahp")
ahpData <- Load("ipads.ahp")
Calculate(ahpData)
Analyze(ahpData)
AnalyzeTable(ahpData)
